#! /bin/bash 


if [ $ENTORNO_INICIALIZADO ]; then
	echo "Entorno ya inicializado"
	glog iniciar E "Entorno ya inicializado" 
	exit 13
fi

# TODO Leer las variables de un archivo de configuracion.

export PATH=$PATH:.
export LOGDIR=.
export MAXLOG=1024
export CANLOOP=100
export ENTORNO_INICIALIZADO=1

# Corre detectar en modo background.
detectar &

echo "Entorno inicializado. Ejecutar exit para salir."
bash
